### PR TITLE
[Feature] Modernize

### PR DESCRIPTION
**Pull request by dougdellolio**

### CODE REVIEW

**Comment by dougdellolio** [comment]
@ealouie @kakawangza modernizes the look of it. still working on the spacing between the title - can't seem to find the cause of it. let me know what you think.

**Comment by ealouie** [comment]
@dougdellolio @kakawangza Looks good!

**Comment by ChoJeyung** [comment]
Is the lane 88
$('#history').append('<ul class="a"><li type = "circle"><a href="'+
result[i] +'">'+ result[i] +'</a></li></ul>');
?

**Comment by dougdellolio** [comment]
@kakawangza checkout master now and make sure you pull the latest and work off of that. also make sure you checkout new branch and commit changes to the branch. i think you are committing straight to master

**Comment by ChoJeyung** [comment]
Ouch, my bad

**Comment by ChoJeyung** [comment]
Error in response to storage.get: TypeError: Cannot read property 'length'
of undefined
    at Object.callback
(chrome-extension://alcnpibgbclbcccgackcimpeapbbdhij/popup.js:93:41)
    at HTMLDocument.<anonymous>
(chrome-extension://alcnpibgbclbcccgackcimpeapbbdhij/popup.js:91:23)

At the moment, there is an error.

**Comment by dougdellolio** [comment]
@kakawangza its fixed now. I think you deleted a line and merged. i reverted it though. #14

**Comment by ChoJeyung** [comment]
It still shows same error in chrome console.

**Comment by dougdellolio** [comment]
@kakawangza make sure you pull the latest. seems to be working on mine.

**Pull request merged**
