### PR TITLE
[Feature] Shows when deleted

### PR DESCRIPTION
**Pull request by dougdellolio**

### CODE REVIEW

**Comment by ChoJeyung** [comment]
Is this the latest merged version?
2015. 12. 7. 오전 7:26에 "Doug Dellolio" notifications@github.com님이 작성:

**Comment by ealouie** [comment]
Yeah, it is.

**Comment by ChoJeyung** [comment]
Is the history working properly?

**Comment by dougdellolio** [comment]
yes it is. gonna help you out on this last part, the summary bit.

**Comment by ChoJeyung** [comment]
Wow so it does save data when chrome closes
What should I add?

**Pull request merged**
